name: Waka Readme

on:
  schedule:
    # Runs at 6am BJS
    - cron: '00 22 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          SHOW_PROFILE_VIEWS: "False"
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
          IGNORED_REPOS: "jackgdn.github.io"
          # SHOW_PROJECTS: "False"
          # SHOW_LANGUAGE_PER_REPO: "False"
          # SHOW_LOC_CHART: "False"
          
